version: '3'
services:
  postgres:
    build: ./db
    container_name: postgres
    ports:
      - '5432:5432'
    networks: 
      - ft_transcendence
    volumes: 
      - pg-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - '3000:3000'
    networks: 
      - ft_transcendence
    depends_on: 
      - postgres
  
  #frontend:
  #  build: ./frontend
  #  ports:
  #    - '3001:3001'
  #  networks:
  #    - ft_transcendence
  #  depends_on:
  #    - backend

volumes:
  pg-data:

networks:
  ft_transcendence:
    driver: bridge
    name: ft_transcendence